<Player>:
  canvas:
    Color:
      rgb: 1, 1, 1
    Ellipse:
      size: self.width + 4, self.height + 4
      pos: self.x - 2, self.y - 2
    Color:
      rgb: self.p_color
    Ellipse:
      size: self.size
      pos: self.pos

<Content>:
  user: user

  canvas:
    Color:
      rgb: 0,1,0.5
    Rectangle:
      size: root.size
      pos: root.pos

  Player:
    id: user
    center: root.center
    size: 10, 10
